mDotO = 2.33; % [kg/s]mass flow of injector
Cd = .7; % Discharge Coefficient
dP = 85; % (psi) change in pressure
p = 1.22; % (g/cm^3) density
dP_pa = dP * 6894.76 ; % Pa
Ao = (mDotO) / (Cd * sqrt(2 * p * dP_pa)) ;
Dio = .02 ; % m
Aio = pi * (Dio^2) / u ;
N = Ao / Aio ; % 
